### ISSUE TITLE
i can't login on Patch 3.7.11

### ISSUE THREAD

**Issue by COLONEROz** [theli-ua/garenahon#11]
Last login: Tue Oct 13 00:45:48 on ttys000
COLONEROz:~ COLONEROz$ /Applications/Heroes\ of\ Newerth.app/sea.command ; exit;
/Applications/Heroes of Newerth.app ~
Current version
	
f3d6552d01218b2fc08936e9c4d588e78f27dfa7
Latest version
	
f3d6552d01218b2fc08936e9c4d588e78f27dfa7
Already up to date, nothing to update
checking for HoN updates
Found latest appropriate version: 3.7.11.0
current version:
3.7.11.0
started httpserver...
starging hon
Patching interface
2015-10-13 01:08:26.018 HoN[2542:476045] 01:08:26.018 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
warning: The VAD has been replaced by a hack pending a complete rewrite
127.0.0.1 - - [13/Oct/2015 01:08:40] "POST /client_requester.php?f=auth HTTP/1.1" 200 -
127.0.0.1 - - [13/Oct/2015 01:08:41] "POST /client_requester.php?f=auth HTTP/1.1" 200 -
hon exited, stopping masterserver and cleaning up
~
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by Lawliet666** [comment]
+

**Comment by theli-ua** [comment]
should be fixed
I dont really play hon for several years by now,
